import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import Header from "@/components/Header";
// import Footer from "@/components/Footer";

const font = Inter({
  weight : ["100","200","300","400","500","600","700","800","900"],
  subsets : ["latin"]
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} antialiased bg-bg-main`}>
        {/* <Header/>
        {children}
        <Footer/> */}
        <h1>site in progress</h1>
      </body>
    </html>
  );
}
